export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const UPDATE_LOGIN_INFO = "UPDATE_LOGIN_INFO";

export const COMPANY_JOB_DETAILS = "COMPANY_JOB_DETAILS";

export const COMPANY_EVENT_DETAILS = "COMPANY_EVENT_DETAILS";